name: n2t_hdl
description: A library for parsing HDL code.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  petitparser: ^6.0.2
  dart_vcd: ^1.0.3
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
